name: fossa

on:
  push: {}
  pull_request: {}

permissions:
  contents: write
  packages: write

jobs:
  fossa-scan:
    runs-on: ["org--${{ github.repository_owner }}--amd64-containers"]
    container: ubuntu:22.04
    steps:
#    - name : Read vault secrets
#      uses : rancher-eio/read-vault-secrets@main
#      with:
#        secrets: |
#          secret/data/github/repo/${{ github.repository }}/fossa/credentials api_key | FOSSA_API_KEY ;
    - name : Checkout repository
      # https://github.com/actions/checkout/releases/tag/v4.1.1
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name : Run Fossa
      # https://github.com/fossas/fossa-action/releases/tag/v1.3.3
      uses: fossas/fossa-action@47ef11b1e1e3812e88dae436ccbd2d0cbd1adab0 # v1.3.3
      with:
        api-key: ${{ secrets.FOSSA_API_KEY }}
      # Note: fossa runs a scan by default
